//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarvinApp.Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnimalTypeReadableNames_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalTypeReadableNames_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarvinApp.Presentation.AnimalTypeReadableNames_RU", typeof(AnimalTypeReadableNames_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принадлежащие Императору.
        /// </summary>
        internal static string Emperors {
            get {
                return ResourceManager.GetString("Emperors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разбившие цветочную вазу.
        /// </summary>
        internal static string FlowerVaseBreakers {
            get {
                return ResourceManager.GetString("FlowerVaseBreakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похожие издали на мух.
        /// </summary>
        internal static string LookingLikeFlies {
            get {
                return ResourceManager.GetString("LookingLikeFlies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молочные поросята.
        /// </summary>
        internal static string Piglets {
            get {
                return ResourceManager.GetString("Piglets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бегающие как сумасшедшие.
        /// </summary>
        internal static string RunningLikeCrazy {
            get {
                return ResourceManager.GetString("RunningLikeCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бродячие собаки.
        /// </summary>
        internal static string StrayDogs {
            get {
                return ResourceManager.GetString("StrayDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сказочные.
        /// </summary>
        internal static string Tale {
            get {
                return ResourceManager.GetString("Tale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приручённые.
        /// </summary>
        internal static string Tamed {
            get {
                return ResourceManager.GetString("Tamed", resourceCulture);
            }
        }
    }
}
